const text=document.getElementById('text'),size=document.getElementById('size'),color=document.getElementById('color'),box=document.getElementById('qrcode'),empty=document.getElementById('empty'),logo=document.getElementById('logo'),fileName=document.getElementById('fileName'),styleSelect=document.getElementById('style');
const treeCanvas=document.getElementById('treeCanvas'),heroCanvas=document.getElementById('heroTree');
const pngTree=document.getElementById('downloadTreePng'),pngQr=document.getElementById('downloadQrPng'),svg=document.getElementById('downloadSvg'),gifBtn=document.getElementById('downloadGif'),videoBtn=document.getElementById('downloadVideo'),copy=document.getElementById('copy'),status=document.getElementById('exportStatus');
const palettes={forest:{dark:0x315b42,light:0x8fb99a,trunk:0x72563d},emerald:{dark:0x17624e,light:0x78c9a8,trunk:0x6b5139},night:{dark:0x244936,light:0xb7a65a,trunk:0x664b38}};
let qrCanvas=null,logoData=null,qrTexture=null,seed=Math.random()*10000,renderer=null,scene=null,camera=null,treeRoot=null,raf=0,interactiveCanvas=null,mouseX=0,mouseY=0;

function generate(){const value=text.value.trim();if(!value){text.focus();return}box.innerHTML='';new QRCode(box,{text:value,width:+size.value,height:+size.value,colorDark:color.value,colorLight:'#fff',correctLevel:QRCode.CorrectLevel.H});empty.style.display='none';seed=Math.random()*10000;setTimeout(()=>{qrCanvas=box.querySelector('canvas');if(!qrCanvas)return;if(logoData)drawLogo(qrCanvas,logoData).then(refreshQR);else refreshQR();[pngTree,pngQr,svg,gifBtn,videoBtn,copy].forEach(b=>b.disabled=false)},80)}
function drawLogo(c,data){return new Promise(resolve=>{const img=new Image();img.onload=()=>{const ctx=c.getContext('2d'),s=Math.floor(c.width*.18),x=(c.width-s)/2,y=(c.height-s)/2;ctx.fillStyle='#fff';roundRect(ctx,x-8,y-8,s+16,s+16,11);ctx.drawImage(img,x,y,s,s);resolve()};img.src=data})}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);ctx.closePath();ctx.fill()}
function refreshQR(){if(!qrCanvas||!renderer)return;qrTexture=new THREE.CanvasTexture(qrCanvas);qrTexture.colorSpace=THREE.SRGBColorSpace;const old=document.querySelector('#qrcode canvas');if(old)old.style.display='none';}

function init3D(target){const r=new THREE.WebGLRenderer({canvas:target,antialias:true,alpha:false,preserveDrawingBuffer:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.outputEncoding=THREE.sRGBEncoding;r.setClearColor(0xe8f0e5,1);const s=new THREE.Scene();const c=new THREE.PerspectiveCamera(35,target.clientWidth/Math.max(target.clientHeight,1),.1,100);c.position.set(0,1.8,10);c.lookAt(0,1.8,0);s.add(new THREE.HemisphereLight(0xf5ffe9,0x415747,1.5));const sun=new THREE.DirectionalLight(0xfff3cf,2.1);sun.position.set(-4,7,5);s.add(sun);const root=new THREE.Group();s.add(root);return{renderer:r,scene:s,camera:c,root}};
function makeTree(root,variant){while(root.children.length)root.remove(root.children[0]);const p=palettes[variant]||palettes.forest;const trunkMat=new THREE.MeshStandardMaterial({color:p.trunk,roughness:.88});const darkMat=new THREE.MeshStandardMaterial({color:p.dark,roughness:.7});const lightMat=new THREE.MeshStandardMaterial({color:p.light,roughness:.65});
function branch(parent,a,b,r1,r2){const A=new THREE.Vector3(...a),B=new THREE.Vector3(...b),v=B.clone().sub(A),len=v.length(),g=new THREE.CylinderGeometry(r2,r1,len,8);const m=new THREE.Mesh(g,trunkMat);m.position.copy(A).add(B).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());parent.add(m);return m}
const trunk=branch(root,[0,0,0],[0,3.8,0],.42,.22);trunk.name='trunk';
const branches=[[[0,2.0,0],[-2.1,3.5,.1]],[[0,2.55,0],[2.2,3.8,-.1]],[[0,3.0,0],[-1.35,4.7,.05]],[[0,3.3,0],[1.25,4.95,.1]],[[0,3.55,0],[-.15,5.55,0]]];
branches.forEach((pair,i)=>{const b=branch(root,pair[0],pair[1],.18,.07);b.name='branch'+i});
const clusters=[[-2.35,3.55,.15,.92,darkMat],[-1.25,4.75,.05,1.0,lightMat],[2.4,3.85,-.1,1.02,darkMat],[1.3,4.95,.1,.92,lightMat],[-.15,5.65,0,1.05,darkMat],[-3.0,4.35,.2,.62,lightMat],[2.9,4.55,-.15,.65,lightMat],[.1,4.2,.35,.7,darkMat]];
clusters.forEach((q,i)=>{const g=new THREE.Group();g.position.set(q[0],q[1],q[2]);g.name='leafCluster'+i;for(let j=0;j<7;j++){const leaf=new THREE.Mesh(new THREE.IcosahedronGeometry(q[3]*(.48+Math.random()*.35),1),q[4]);leaf.position.set((Math.random()-.5)*q[3],(Math.random()-.5)*q[3]*.65,(Math.random()-.5)*q[3]);leaf.rotation.set(Math.random(),Math.random(),Math.random());g.add(leaf)}root.add(g)});
const ground=new THREE.Mesh(new THREE.CylinderGeometry(3.8,4.2,.18,48),new THREE.MeshStandardMaterial({color:0xc8d6c6,roughness:1}));ground.position.y=-.12;root.add(ground);
}
function addQR(root){if(!qrTexture)return;if(root.getObjectByName('qrCard'))root.remove(root.getObjectByName('qrCard'));const g=new THREE.Group();g.name='qrCard';const plane=new THREE.Mesh(new THREE.PlaneGeometry(2.65,2.65),new THREE.MeshBasicMaterial({map:qrTexture,side:THREE.DoubleSide,transparent:true}));plane.position.set(0,2.85,1.35);g.add(plane);const frame=new THREE.Mesh(new THREE.BoxGeometry(2.9,.12,2.9),new THREE.MeshStandardMaterial({color:0xfafcf7,roughness:.6}));frame.position.set(0,2.85,1.3);g.add(frame);root.add(g)}
function setup(target,isHero=false){const pack=init3D(target);pack.renderer.setSize(target.clientWidth||760,target.clientHeight||620,false);makeTree(pack.root,styleSelect.value);if(qrTexture&&!isHero)addQR(pack.root);target.addEventListener('pointermove',e=>{const rect=target.getBoundingClientRect();mouseX=((e.clientX-rect.left)/rect.width-.5)*2;mouseY=((e.clientY-rect.top)/rect.height-.5)*2});return pack}

function render(){if(!renderer)return;const t=performance.now()*.001;treeRoot.rotation.y=mouseX*.18+Math.sin(t*.25)*.10;treeRoot.rotation.z=Math.sin(t*.7)*.018;treeRoot.position.y=Math.sin(t*.55)*.04;treeRoot.traverse(o=>{if(o.name.startsWith('leafCluster')){o.rotation.z=Math.sin(t*1.15+o.id)*.035;o.rotation.x=Math.cos(t*.9+o.id)*.025}});if(qrTexture){const q=treeRoot.getObjectByName('qrCard');if(q){q.rotation.y=mouseX*.08;q.rotation.x=-mouseY*.04}}camera.position.x=mouseX*.45;camera.position.y=1.8-mouseY*.2;camera.lookAt(0,2.8,0);renderer.render(scene,camera)}
function loop(){cancelAnimationFrame(raf);const tick=()=>{render();if(heroPack)renderPack(heroPack);raf=requestAnimationFrame(tick)};raf=requestAnimationFrame(tick)}
function renderPack(pack){const t=performance.now()*.001;pack.root.rotation.y=Math.sin(t*.25)*.10;pack.root.rotation.z=Math.sin(t*.7)*.018;pack.root.position.y=Math.sin(t*.55)*.04;pack.root.traverse(o=>{if(o.name.startsWith('leafCluster')){o.rotation.z=Math.sin(t*1.15+o.id)*.035;o.rotation.x=Math.cos(t*.9+o.id)*.025}});pack.camera.lookAt(0,2.8,0);pack.renderer.render(pack.scene,pack.camera)}
let heroPack=null;
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1200)}
function compositeTree(){const out=document.createElement('canvas');out.width=1200;out.height=900;const ctx=out.getContext('2d');ctx.fillStyle='#e8f0e5';ctx.fillRect(0,0,out.width,out.height);ctx.drawImage(treeCanvas,0,0,out.width,out.height);if(qrCanvas){const q=280;ctx.fillStyle='#fff';roundRect(ctx,(out.width-q)/2-16,450-16,q+32,q+32,18);ctx.drawImage(qrCanvas,(out.width-q)/2,450,q,q)}return out}
pngTree.addEventListener('click',()=>{const out=compositeTree();out.toBlob(b=>downloadBlob(b,'qr2tree-tree.png'),'image/png')});
pngQr.addEventListener('click',()=>qrCanvas?.toBlob(b=>downloadBlob(b,'qr2tree-qr.png'),'image/png'));
svg.addEventListener('click',()=>{if(!qrCanvas)return;const d=qrCanvas.toDataURL('image/png'),s=qrCanvas.width;const src=`<svg xmlns="http://www.w3.org/2000/svg" width="${s}" height="${s}" viewBox="0 0 ${s} ${s}"><image href="${d}" width="${s}" height="${s}"/></svg>`;downloadBlob(new Blob([src],{type:'image/svg+xml'}),'qr2tree-qr.svg')});
videoBtn.addEventListener('click',()=>{if(!renderer||!qrCanvas)return;const canvas=treeCanvas,stream=canvas.captureStream?.(30);if(!stream||!window.MediaRecorder){status.textContent='Video recording is not supported in this browser.';return}let mime='video/webm';if(!MediaRecorder.isTypeSupported(mime))mime='video/webm;codecs=vp8';const rec=new MediaRecorder(stream,{mimeType:mime}),chunks=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{downloadBlob(new Blob(chunks,{type:mime}),'qr2tree.webm');status.textContent='Video ready.'};rec.start();status.textContent='Recording 4 seconds…';setTimeout(()=>{rec.stop();status.textContent='Finishing video…'},4000)});
gifBtn.addEventListener('click',()=>{if(!window.GIF||!renderer)return;const c=document.createElement('canvas');c.width=600;c.height=520;const ctx=c.getContext('2d');const frames=18;status.textContent='Creating GIF…';const gif=new GIF({workers:2,quality:10,width:c.width,height:c.height,workerScript:'https://cdnjs.cloudflare.com/ajax/libs/gif.js/0.2.0/gif.worker.js'});for(let i=0;i<frames;i++){const f=document.createElement('canvas');f.width=c.width;f.height=c.height;const fc=f.getContext('2d');fc.drawImage(treeCanvas,0,0,c.width,c.height);if(qrCanvas){const q=150;fc.fillStyle='#fff';roundRect(fc,(c.width-q)/2-8,260-8,q+16,q+16,10);fc.drawImage(qrCanvas,(c.width-q)/2,260,q,q)}gif.addFrame(f,{delay:80,copy:true})}gif.on('finished',b=>{downloadBlob(b,'qr2tree.gif');status.textContent='GIF ready.'});gif.render()});
copy.addEventListener('click',async()=>{await navigator.clipboard.writeText(text.value.trim());const old=copy.textContent;copy.textContent='Copied ✓';setTimeout(()=>copy.textContent=old,1200)});
logo.addEventListener('change',()=>{const f=logo.files?.[0];if(!f)return;fileName.textContent=f.name;const r=new FileReader();r.onload=()=>{logoData=r.result;generate()};r.readAsDataURL(f)});
size.addEventListener('change',generate);color.addEventListener('input',generate);styleSelect.addEventListener('change',()=>{if(treeRoot)makeTree(treeRoot,styleSelect.value);generate()});document.getElementById('generate').addEventListener('click',generate);text.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')generate()});
let arabic=false;document.getElementById('lang').addEventListener('click',()=>{arabic=!arabic;document.documentElement.lang=arabic?'ar':'en';document.body.dir=arabic?'rtl':'ltr';document.querySelector('.hero h1').innerHTML=arabic?'حوّل رمز QR<br><em>إلى شجرة ثلاثية الأبعاد حيّة.</em>':'Turn your QR code<br><em>into a living 3D tree.</em>';document.querySelector('.hero p').textContent=arabic?'أدخل رابطًا أو نصًا وشاهد شجرة ثلاثية الأبعاد تتحرك بهدوء حول QR الحقيقي. احفظها كصورة أو GIF أو فيديو، أو احفظ QR وحده.':'Enter a link or text and watch a real-time 3D tree move gently around your QR. Export it as an image, GIF or video, or save the clean QR separately.';document.querySelector('.cta').innerHTML=arabic?'أنشئ شجرة QR <span>←</span>':'Create my QR tree <span>→</span>'});
let audioCtx;function startAmbient(){if(audioCtx){audioCtx.resume();return}audioCtx=new(window.AudioContext||window.webkitAudioContext)();const master=audioCtx.createGain();master.gain.value=.025;master.connect(audioCtx.destination);const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=95;g.gain.value=.035;o.connect(g).connect(master);o.start()}
document.getElementById('sound').addEventListener('click',()=>{const b=document.getElementById('sound');if(!audioCtx||audioCtx.state==='suspended'){startAmbient();b.textContent='♫ Ambient sound: on';b.setAttribute('aria-pressed','true')}else{audioCtx.suspend();b.textContent='♫ Ambient sound: off';b.setAttribute('aria-pressed','false')}});
function boot(){const hp=setup(heroCanvas,true);heroPack=hp;const main=setup(treeCanvas,false);renderer=main.renderer;scene=main.scene;camera=main.camera;treeRoot=main.root;loop();generate()}
boot();